import type { Locale } from "./types";

type Copy = Record<string, { en: string; ar: string }>;

export const copy = {
  navAtlas: { en: "Show atlas", ar: "عرض الأطلس" },
  navDestinations: { en: "Destinations", ar: "الوجهات" },
  navStories: { en: "Stories", ar: "القصص" },
  navTrips: { en: "Trips", ar: "الرحلات" },
  navGuides: { en: "Guides", ar: "الأدلة" },
  navBookmarks: { en: "Bookmarks", ar: "المحفوظات" },
  navSearch: { en: "Search", ar: "بحث" },
  heroKicker: {
    en: "A digital atlas of East Africa and beyond",
    ar: "أطلس رقمي لشرق أفريقيا وما بعدها",
  },
  heroByline: {
    en: "Field notes by Maryam Rashid — weekly dispatches from the road",
    ar: "ملاحظات ميدانية لمريم رشيد — رسائل أسبوعية من الطريق",
  },
  filterCountry: { en: "Country", ar: "الدولة" },
  filterType: { en: "Content type", ar: "نوع المحتوى" },
  filterCategory: { en: "Category", ar: "التصنيف" },
  filterAll: { en: "All", ar: "الكل" },
  featuredDestinations: { en: "Featured destinations", ar: "وجهات مختارة" },
  featuredJourney: { en: "Featured journey", ar: "رحلة مختارة" },
  latestStories: { en: "Latest field notes", ar: "أحدث الملاحظات" },
  collections: { en: "Collections", ar: "مجموعات" },
  newsletterTitle: { en: "Weekly dispatch", ar: "نشرة أسبوعية" },
  newsletterBody: {
    en: "One letter a week. No itinerary spam. Just the next coordinate, photograph, and note from the road.",
    ar: "رسالة واحدة أسبوعياً. بلا إعلانات مسارات. الإحداثي التالي والصورة والملاحظة من الطريق.",
  },
  newsletterCta: { en: "Subscribe", ar: "اشترك" },
  newsletterPlaceholder: { en: "Email address", ar: "البريد الإلكتروني" },
  newsletterSuccess: { en: "Subscribed successfully.", ar: "تم الاشتراك بنجاح." },
  newsletterError: { en: "Please enter a valid email.", ar: "يرجى إدخال بريد صالح." },
  aboutTitle: { en: "About Maryam", ar: "عن مريم" },
  readStory: { en: "Read the story", ar: "اقرأ القصة" },
  exploreJourney: { en: "Explore journey", ar: "استكشف الرحلة" },
  viewDestination: { en: "Open destination", ar: "افتح الوجهة" },
  bookmark: { en: "Bookmark", ar: "حفظ" },
  bookmarked: { en: "Saved", ar: "محفوظ" },
  share: { en: "Share", ar: "شارك" },
  copied: { en: "Link copied", ar: "تم نسخ الرابط" },
  practical: { en: "Practical notes", ar: "ملاحظات عملية" },
  bestTime: { en: "Best time", ar: "أفضل وقت" },
  duration: { en: "Duration", ar: "المدة" },
  currency: { en: "Currency", ar: "العملة" },
  stay: { en: "Stay", ar: "الإقامة" },
  food: { en: "Food", ar: "الطعام" },
  activity: { en: "Activity", ar: "النشاط" },
  transport: { en: "Transport", ar: "التنقل" },
  tips: { en: "Useful tips", ar: "نصائح" },
  related: { en: "Continue exploring", ar: "تابع الاستكشاف" },
  storiesCount: { en: "stories", ar: "قصص" },
  emptyBookmarks: {
    en: "No saved stories yet. Bookmark from any field note.",
    ar: "لا توجد قصص محفوظة بعد. احفظ من أي ملاحظة ميدانية.",
  },
  searchPlaceholder: {
    en: "Search stories, destinations, trips",
    ar: "ابحث في القصص والوجهات والرحلات",
  },
  noResults: { en: "No matches on this coordinate.", ar: "لا توجد نتائج على هذا الإحداثي." },
  listen: { en: "Field audio", ar: "تسجيل ميداني" },
  gallery: { en: "Photographs", ar: "صور" },
  route: { en: "Route", ar: "المسار" },
  timeline: { en: "Timeline", ar: "الجدول الزمني" },
  fallbackMap: {
    en: "Map unavailable — destinations listed below.",
    ar: "الخريطة غير متاحة — الوجهات أدناه.",
  },
  footerLine1: { en: "Sahani.KE · Nairobi / the road", ar: "Sahani.KE · نيروبي / الطريق" },
  footerLine2: { en: "Kenya · Tanzania · Rwanda · Egypt · South Africa · Morocco", ar: "كينيا · تنزانيا · رواندا · مصر · جنوب أفريقيا · المغرب" },
  footerLine3: { en: "Atlas by Maryam Rashid", ar: "أطلس من مريم رشيد" },
  language: { en: "EN", ar: "ع" },
  allCountries: { en: "All countries", ar: "كل الدول" },
  loginTitle: { en: "Editorial desk", ar: "مكتب التحرير" },
  loginCta: { en: "Continue as Maryam Rashid", ar: "المتابعة كمريم رشيد" },
  password: { en: "Desk password", ar: "كلمة مرور المكتب" },
  overview: { en: "Overview", ar: "نظرة عامة" },
  published: { en: "Published", ar: "منشور" },
  draft: { en: "Draft", ar: "مسودة" },
  scheduled: { en: "Scheduled", ar: "مجدول" },
  subscribers: { en: "Subscribers", ar: "المشتركون" },
  logout: { en: "Sign out", ar: "خروج" },
  save: { en: "Save", ar: "حفظ" },
  create: { en: "Create", ar: "إنشاء" },
  preview: { en: "Preview", ar: "معاينة" },
  translations: { en: "Translations", ar: "الترجمات" },
  mediaLibrary: { en: "Media library", ar: "مكتبة الوسائط" },
  settings: { en: "Settings", ar: "الإعدادات" },
  exportCsv: { en: "Export CSV", ar: "تصدير CSV" },
  close: { en: "Close", ar: "إغلاق" },
  openNewsletter: { en: "Join the dispatch", ar: "انضم للنشرة" },
} satisfies Copy;

export function t(key: keyof typeof copy, locale: Locale): string {
  return copy[key][locale];
}
